### ISSUE TITLE
BUG: Can't plot feature importance

### ISSUE THREAD

**Issue by faurholdt** [andersbogsnes/ml_tooling#338]
**Describe the bug**
When calling result.plot.feature_importance() I got a process_execution error from loky.

I can plot using the confusion_matrix method.
---------------------------------------------------------------------------

**To Reproduce**

**Expected behavior**

**Additional context**
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 600, in __call__
    return self.func(*args, **kwargs)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/ml_tooling/metrics/permutation_importance.py", line 24, in _calculate_permutation_scores
    X.iloc[:, col_idx] = temp
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 205, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 540, in _setitem_with_indexer
    setter(labels[0], value)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/indexing.py", line 494, in setter
    self.obj[item] = s
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3487, in __setitem__
    self._set_item(key, value)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/frame.py", line 3565, in _set_item
    NDFrame._set_item(self, key, value)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 3381, in _set_item
    self._data.set(key, value)
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 1090, in set
    blk.set(blk_locs, value_getitem(val_locs))
  File "/home/philip/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/pandas/core/internals/blocks.py", line 380, in set
    self.values[locs] = values
ValueError: assignment destination is read-only
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-215-f1ddecf9d57f> in <module>
----> 1 rf_result.plot.feature_importance()

~/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/ml_tooling/result/viz/baseviz.py in feature_importance(self, n_repeats, values, top_n, bottom_n, n_jobs, **kwargs)
     88             n_repeats=n_repeats,
     89             random_state=self._config.RANDOM_STATE,
---> 90             n_jobs=n_jobs,
     91         )
     92         labels = self._data.train_x.columns

~/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/ml_tooling/metrics/permutation_importance.py in permutation_importance(estimator, X, y, scoring, n_repeats, n_jobs, random_state)
     92             estimator, X, y, col_idx, random_state, n_repeats, scorer
     93         )
---> 94         for col_idx in range(X.shape[1])
     95     )
     96 

~/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1014 
   1015             with self._backend.retrieval_context():
-> 1016                 self.retrieve()
   1017             # Make sure that we get a last message telling us we are done
   1018             elapsed_time = time.time() - self._start_time

~/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    906             try:
    907                 if getattr(self._backend, 'supports_timeout', False):
--> 908                     self._output.extend(job.get(timeout=self.timeout))
    909                 else:
    910                     self._output.extend(job.get())

~/Documents/advanced_analytics/for_p_bil_segmentation/venv/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    552         AsyncResults.get from multiprocessing."""
    553         try:
--> 554             return future.result(timeout=timeout)
    555         except LokyTimeoutError:
    556             raise TimeoutError()

/usr/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/usr/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: assignment destination is read-only

- [x] I have updated ML Tooling to the latest version
- [x] I have checked if this issue has been reported previously

**Comment by andersbogsnes** [comment]
closed by #341
